export const SET_AUTH_STATUS = 'isAuth'
export const SET_AUTH_TOKEN = 'authToken'
export const SET_AUTH_ICP_BALANCE = 'icpBalance'
export const SET_AUTH_WICP_BALANCE = 'wicpBalance'
export const SET_AUTH_PROFILE = 'profile'
export const SET_AUTH_SCROE = 'score'
export const SET_AUTH_AVATAR = 'avatar'
export const SET_COLLECTION_CONFIG = 'collection'
