export const CHANGE_CANVAS_INFO = 'canvasInfo'
export const CHANGE_CANVAS_NFT_INFO = 'nftInfo'
export const CHANGE_NO_CANVAS_NFT_INFO = 'noCanvasNFTInfo'
export const CHANGE_UNDONE_CANVAS = 'undoneCanvas'
export const CHANGE_DONE_CANVAS = 'doneCanvas'
export const CHANGE_PRICE_HIGHEST_INFO = 'priceHighestInfo'
export const CHANGE_MARKET_LAST_INFO = 'marktetLastInfo'
export const CHANGE_COLLECTION_INFO = 'collectionInfo'
export const CHANGE_BLIND_BOX_INFO = 'blindbox'
export const POPULAR_ALONE_CANVAS = '/market/listPopularAloneCanvas'
export const POPULAR_COLLECTIBLES = '/config/popular_collectibles.json'
export const HOME_BANNER_AD = `/config/popular_alone_canvas_ad.json?timestamp=${new Date().getTime()}`
export const POPULAR_TOP_COLLECTIBLES = 'topCollectibles'
export const CHANGE_STAKE_INFO = 'stake'
