export const CHANGE_PIXEL_INFO = 'pixelInfo'
export const CHANGE_NEW_PIXEL_INFO = 'newPixelInfo'
export const CHANGE_IMAGE_PIXEL_INFO = 'imagePixelInfo'
export const CHANGE_IMAGE_POSITION_INFO = 'imagePositionInfo'
export const CHANGE_PIN_PIXEL_INFO = 'pinPixelInfo'
export const CHANGE_EXIST_IMAGE_INFO = 'existImage'
