export const ListingUpdate = 'ListingUpdate'
export const UndownUpdate = 'UndownUpdate'
export const ResetDrawPixel = 'ResetDrawPixel'
export const RefreshCrowdUndone = 'RefreshCrowdUndone'
export const OwnedNFTUpdate = 'OwnedNFTUpdate'
